server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
      locator: 
        enabled: true
      lower-case-service-id: true # Corrected typo
    # gateway:
    #   routes:
    #     - id: AUTH-SERVICE
    #       uri: lb://AUTH-SERVICE  # Use service name from discovery service
    #       predicates:
    #         - Path=/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Set your Eureka server URL
