server:
  port: 80
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: api-gateway
    enabled: true

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILE:dev}  # Sets active profile to the value of SPRING_PROFILE env variable or "dev" if not set
  cloud:
    config:
      fail-fast: true
      label: main
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true

  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URL:http://config-server:8888}  # URL for the config server, defaults to http://config-server:8888  # URL for the config server, defaults to http://config-server:8888
