server:
  port: 80
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: api-gateway
    enabled: true

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILE:dev} # Sets active profile to the value of SPRING_PROFILE env variable or "dev" if not set
  cloud:
    config:
      fail-fast: true
      label: main
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "https://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: get_route
          uri: http://httpbin.org
          predicates:
            - Path=/get

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/auth/**
        - id: homepage-service
          uri: http://localhost:8002
          predicates:
            - Path=/home/**

        - id: media-service
          uri: http://localhost:8003
          predicates:
            - Path=/media/**
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URL:http://config-server:8888} # URL for the config server, defaults to http://config-server:8888  # URL for the config server, defaults to http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
