server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: api-gateway
    enabled: true

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
      locator:
        enabled: true
      lower-case-service-id: true
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "https://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
