version: '3.8'

services:
  config-server:
    build: .
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: default
      # Define other environment variables your config server might need
    restart: always

  # Example of another service that might depend on the Config Server
  # my-service:
  #   image: my-service-image
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  #     SPRING_PROFILES_ACTIVE: default
  #   depends_on:
  #     - config-server
  #   restart: always
