version: "3.8"

services:
  frontend:
    image: gksvp/react-app:latest
    container_name: react-app-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
