server:
  servlet:
    context-path: /home

spring:
  application:
    name: homepage-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URL:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      label: main
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
