server:
  port: 8004
  servlet:
    context-path: /homepage-service

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  config:
    import: "optional:configserver:http://localhost:8888"

  application:
    name: homepage-service
  datasource:
    url: jdbc:mysql://localhost:3306/homepage_service
    username: user_service
    password: Pa$$w0rd@app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans

logging:
  level:
    root: WARN
