server:
  port: 8082
spring:
  application:
    name: messaging-service
  config:
    label: main  
    name: messaging-service
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh  
