spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URL:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      label: main
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true # Optional: discover services in all namespaces
