server:
   port: 8002
  # servlet:
  #   context-path: /api

spring:
  application:
    name: product-service
  config:
    name: product-service
    import: optional:configserver:http://192.168.0.153:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: user_service
    password: Pa$$w0rd@app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Redis Configuration
spring.redis.host: localhost
spring.redis.port: 6379

# Elasticsearch Configuration
spring.data.elasticsearch.cluster-nodes: localhost:9200
