server:
  port: 8003
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  config:
    name: product-service
    import: optional:configserver:http://192.168.0.153:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: user_service
    password: Pa$$w0rd@app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Redis Configuration
spring.data.redis.host: localhost
spring.data.redis.port: 6379
