server:
  port: 8003
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  config:
    name: product-service
    import: configserver:${SPRING_CLOUD_CONFIG_URL:http://config-server:8888}
  profiles:
    active: ${SPRING_PROFILE:dev}

management:
  endpoints:
    web:
      exposure:
        include: "*"
