version: "3.8" # Using latest version of Docker Compose

services:
  mysql:
    image: mysql:latest # Specifying MySQL 9.0 explicitly
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password@root # Use environment variable for root password
      MYSQL_DATABASE: user_service
      MYSQL_USER: user_service
      MYSQL_PASSWORD: password@123456 # Use environment variable for user password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
